### ISSUE TITLE
Creating causal graphs from data not workng

### ISSUE THREAD

**Issue by htoor** [salesforce/PyRCA#39]
So I tried the following code, and got the following error

>>> from pyrca.graphs.causal.pc import PC
>>> model = PC(PC.config_class())
>>> graph_df = model.train(df)
D:\Python\Python310\lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
D:\Python\Python310\lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Depth=13, working on node 14: 100%|██████████████████████████████████████████████████| 15/15 [00:00<00:00, 1299.57it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PyRCA-main\pyrca\graphs\causal\base.py", line 69, in train
    adjacency_df = self._train(df=df, **kwargs)
  File "D:\PyRCA-main\pyrca\graphs\causal\pc.py", line 66, in _train
    assert len(items) == 3
AssertionError

**Comment by yangwenz** [comment]
It seems that there are some data issues. Please make sure that there are no INFs and NaNs in the dataframe.

**Comment by htoor** [comment]
While there is no data in the df that has a NAN or INF,  the issue is on line 66 i.e.

assert len(items) == 3

The previous line is 
items = edge.split()

Almost seems lik e that the code is expecting the number of edges to be 3 and only 3

**Comment by yangwenz** [comment]
First, make sure that the data has no missing values. Second, the column names in the dataframe cannot contain "space" char. This is an issue in the causal discovery package, you may replace " " with "_".

**Comment by yangwenz** [comment]
No problem, and let us know if there are any other issues.

**Comment by htoor** [comment]
I made sure all headings have _ instead of spaces, still the same error

df=pd.read_csv('D:/Python/normal_Data.csv')
>>> from pyrca.graphs.causal.pc import PC
>>> model = PC(PC.config_class())
>>> graph_df = model.train(df)

here is what is a sample from normal_Data.csv

**Comment by yangwenz** [comment]
Could add a small amount of random noise into the data? It seems that some metrics are constants.

**Comment by htoor** [comment]
So is that the reason, we are getting 
assert len(items) == 3
AssertionError

**Comment by htoor** [comment]
Also when added more variance, now it failed with a different error
>>> from pyrca.graphs.causal.pc import PC
>>> model = PC(PC.config_class())
>>> graph_df = model.train(df)
D:\Python\Python310\lib\site-packages\numpy\lib\function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
D:\Python\Python310\lib\site-packages\numpy\lib\function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
Depth=13, working on node 14: 100%|██████████████████████████████████████████████████| 15/15 [00:00<00:00, 2890.76it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PyRCA-main\pyrca\graphs\causal\base.py", line 75, in train
    raise RuntimeError("Orientation of the undirected edges failed.")
**RuntimeError: Orientation of the undirected edges failed.**
>>>

**Comment by yangwenz** [comment]
This error is because the generated graph is not a DAG and these cycles cannot be resolved via PartialDAG2DAG. Please set the parameter "run_pdag2dag" to False.

**Comment by htoor** [comment]
No errors there, but now this fails

from pyrca.applications.example.rca import RCAEngine
engine = RCAEngine()
engine.build_causal_graph(
    df=df,
    run_pdag2dag=False,
    max_num_points=5000000,
    verbose=False
)

AssertionError                            Traceback (most recent call last)
Cell In[30], line 3
      1 from pyrca.applications.example.rca import RCAEngine
      2 engine = RCAEngine()
----> 3 engine.build_causal_graph(
      4     df=df,
      5     run_pdag2dag=False,
      6     max_num_points=5000000,
      7     verbose=False
      8 )
      9 bn = engine.train_bayesian_network(dfs=[df])
     10 bn.print_probabilities()

File D:\Python\anaconda3\lib\site-packages\pyrca\applications\example\rca.py:97, in RCAEngine.build_causal_graph(self, df, domain_knowledge_file, run_pdag2dag, max_num_points, method_class, verbose, **kwargs)
     88     method_class = PC
     89 model = method_class(
     90     method_class.config_class(
     91         domain_knowledge_file=domain_knowledge_file,
   (...)
     95     )
     96 )
---> 97 adjacency_df = model.train(df)
     98 adjacency_df.to_pickle(os.path.join(self.model_dir, self.adjacency_df_filename))
     99 PC.dump_to_tetrad_json(adjacency_df, self.model_dir)

File D:\Python\anaconda3\lib\site-packages\pyrca\graphs\causal\base.py:62, in CausalModel.train(self, df, **kwargs)
     59 if self.config.domain_knowledge_file:
     60     parser = DomainParser(self.config.domain_knowledge_file)
     61     adjacency_df = self._train(
---> 62         df=df, forbids=parser.get_forbid_links(df.columns), requires=parser.get_require_links(), **kwargs
     63     )
     64 else:
     65     if "forbids" not in kwargs:

File D:\Python\anaconda3\lib\site-packages\pyrca\utils\domain.py:64, in DomainParser.get_forbid_links(self, graph_nodes, process_root_leaf)
     62 assert graph_nodes is not None, "`graph_nodes` cannot be None."
     63 for u in leaf_nodes:
---> 64     assert u in graph_nodes, f"{u} is not in `all_nodes`"
     65     for v in graph_nodes:
     66         if u != v:

AssertionError: apt is not in `all_nodes`

**Comment by yangwenz** [comment]
The RCAEngine is just an example to show how to use PyRCA in real-world applications. You need to change it according to your use case.

**Comment by htoor** [comment]
Yes, and I muted the logic which was forcing the example domain_knowledge file if none was provided. 

But now I see this error

from pyrca.applications.example.rca import RCAEngine
engine = RCAEngine()
engine.build_causal_graph(
    df=df,
    run_pdag2dag=False,
    max_num_points=5000000,
    verbose=True
)
bn = engine.train_bayesian_network(dfs=[df])
bn.print_probabilities()

ValueError                                Traceback (most recent call last)
File D:\Python\anaconda3\lib\site-packages\networkx\convert.py:172, in to_networkx_graph(data, create_using, multigraph_input)
    171 try:
--> 172     return from_edgelist(data, create_using=create_using)
    173 except Exception as err:

File D:\Python\anaconda3\lib\site-packages\networkx\convert.py:490, in from_edgelist(edgelist, create_using)
    489 G = nx.empty_graph(0, create_using)
--> 490 G.add_edges_from(edgelist)
    491 return G

File D:\Python\anaconda3\lib\site-packages\pyrca\thirdparty\pgmpy\base\DAG.py:285, in DAG.add_edges_from(self, ebunch, weights)
    284 for edge in ebunch:
--> 285     self.add_edge(edge[0], edge[1])

File D:\Python\anaconda3\lib\site-packages\pyrca\thirdparty\pgmpy\models\BayesianModel.py:124, in BayesianModel.add_edge(self, u, v, **kwargs)
    123 if u in self.nodes() and v in self.nodes() and nx.has_path(self, v, u):
--> 124     raise ValueError(
    125         "Loops are not allowed. Adding the edge from (%s->%s) forms a loop."
    126         % (u, v)
    127     )
    128 else:

ValueError: Loops are not allowed. Adding the edge from (Wait_Time->FedEx) forms a loop.

The above exception was the direct cause of the following exception:

NetworkXError                             Traceback (most recent call last)
Cell In[3], line 9
      2 engine = RCAEngine()
      3 engine.build_causal_graph(
      4     df=df,
      5     run_pdag2dag=False,
      6     max_num_points=5000000,
      7     verbose=True
      8 )
----> 9 bn = engine.train_bayesian_network(dfs=[df])
     10 bn.print_probabilities()

File D:\Python\anaconda3\lib\site-packages\pyrca\applications\example\rca.py:142, in RCAEngine.train_bayesian_network(self, dfs, domain_knowledge_file, config_file, verbose)
    139 if verbose:
    140     self.logger.info(f"The training parameters for the Bayesian network: {params}")
--> 142 bayesian_network = BayesianNetwork(
    143     BayesianNetworkConfig(
    144         graph=graph,
    145         default_sigma=params["default_sigma"],
    146         thres_win_size=params["thres_win_size"],
    147         thres_reduce_func=params["thres_reduce_func"],
    148         sigmas=params.get("sigmas", {}),
    149     )
    150 )
    151 bayesian_network.train(dfs=dfs)
    152 bayesian_network.add_root_causes(domain.get_root_causes())

File D:\Python\anaconda3\lib\site-packages\pyrca\analyzers\bayesian.py:78, in BayesianNetwork.__init__(self, config)
     76 else:
     77     self.graph = config.graph
---> 78 self.bayesian_model = self._build_bayesian_network(self.graph)
     79 self.root_nodes = []

File D:\Python\anaconda3\lib\site-packages\pyrca\analyzers\bayesian.py:92, in BayesianNetwork._build_bayesian_network(graph)
     90         for p in parents:
     91             edges.append((p, node))
---> 92     return BayesianModel(ebunch=edges)
     93 return None

File D:\Python\anaconda3\lib\site-packages\pyrca\thirdparty\pgmpy\models\BayesianModel.py:98, in BayesianModel.__init__(self, ebunch, latents)
     30 def __init__(self, ebunch=None, latents=set()):
     31     """
     32     Initializes a Bayesian Model.
     33     A models stores nodes and edges with conditional probability
   (...)
     96     3
     97     """
---> 98     super(BayesianModel, self).__init__(ebunch=ebunch, latents=latents)
     99     self.cpds = []
    100     self.cardinalities = defaultdict(int)

File D:\Python\anaconda3\lib\site-packages\pyrca\thirdparty\pgmpy\base\DAG.py:74, in DAG.__init__(self, ebunch, latents)
     73 def __init__(self, ebunch=None, latents=set()):
---> 74     super(DAG, self).__init__(ebunch)
     75     self.latents = set(latents)
     76     cycles = []

File D:\Python\anaconda3\lib\site-packages\networkx\classes\digraph.py:366, in DiGraph.__init__(self, incoming_graph_data, **attr)
    362 # Note: self._succ = self._adj  # successor
    363 
    364 # attempt to load graph with data
    365 if incoming_graph_data is not None:
--> 366     convert.to_networkx_graph(incoming_graph_data, create_using=self)
    367 # load graph attributes (must be after convert)
    368 self.graph.update(attr)

File D:\Python\anaconda3\lib\site-packages\networkx\convert.py:174, in to_networkx_graph(data, create_using, multigraph_input)
    172         return from_edgelist(data, create_using=create_using)
    173     except Exception as err:
--> 174         raise nx.NetworkXError("Input is not a valid edge list") from err
    176 raise nx.NetworkXError("Input is not a known data type for conversion.")

NetworkXError: Input is not a valid edge list

**Comment by yangwenz** [comment]
The graph used in Bayesian network must be a DAG. If it is not a DAG, it will raise the errors.

**Comment by yangwenz** [comment]
Like this error: "ValueError: Loops are not allowed. Adding the edge from (Wait_Time->FedEx) forms a loop."

**Comment by htoor** [comment]
So, I was trying to determine the graph using pyrca . What should I use instead to simply get the graph first ? Also if it turns to not be DAG, then what model should I use instead?.

**Comment by yangwenz** [comment]
You can try FGES but you need to add domain knowledge when generating the graph because there exists constant metrics. The causal discovery algorithms cannot do everything because of data issues.

**Comment by htoor** [comment]
So does the domain info need to be in YAML file, or can I just provide a Causal graph as a DIGraph object?

**Comment by yangwenz** [comment]
Yes, if you already have a graph, you don't need to run causal discovery. You can just apply RCA methods with it.

**Comment by htoor** [comment]
So the graph is in networkx format. How do I use it? Also, I was able to use the domain knowledge yaml, and data, and graph it produced was quite wrong  see below 
![pyrcaGraph](https://github.com/salesforce/PyRCA/assets/352717/91f2eace-aa40-40be-bb30-fcc0932fab77)

where it should be 
![networkxGraph](https://github.com/salesforce/PyRCA/assets/352717/f2fd80aa-68bd-4ac6-95e7-37819025b469)

Also, it appears that Bayesian neotwrk only work with binary data. Is that true. What is a good model for category data with multiple valeus or range of vales?

**Comment by yangwenz** [comment]
The graph can be a pandas dataframe (adjacency matrix). For categorical data, you may try FGES or PC with discreted value support. You can try this tool: https://github.com/cmu-phil/tetrad. But it is common that causal discovery results are not quite reliable.

**Comment by htoor** [comment]
Can you expand on "it is common that causal discovery results are not quite reliable."

**Comment by yangwenz** [comment]
These methods are statistics methods which requires many assumption on causal models and data properties. The real-world data usually doesn't satisfy these assumptions. Therefore, the results may not be the same as the ground-truth.

**Comment by htoor** [comment]
So then which models or approaches are better suited for the real world scenarios?

**Comment by yangwenz** [comment]
It depends on the data properties, it is hard to say which one is better. The most common used ones are PC and FGES.

**Comment by htoor** [comment]
The other options I am looking into are supervised learning on labeled data. The problem I have with that is model obsolescence over time. This where I understood that a causal model would, which has domain knowledge and not just a weights and biases, would make the model more resilient.
