### ISSUE TITLE
train the example file error

### ISSUE THREAD

**Issue by ghost** [salesforce/PyRCA#53]
use rca.py to train example file called example.csv
In the rca.py

```
  import dataset 
  df = dataset.load_data('data', 'example.csv')
    engine = RCAEngine()
    engine.build_causal_graph(
        df=df,
        run_pdag2dag=True,
        max_num_points=5000000,
        verbose=True
    )
    bn = engine.train_bayesian_network(dfs=[df])
    bn.print_probabilities()

```
error in the **engine.train_bayesian_network** statement: 

```
Traceback (most recent call last):
  File "C:/PyCharm Community Edition 2022.2.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\PyCharm Community Edition 2022.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/1000260871/Desktop/root cause analysis/PyRCA-main/pyrca/applications/example/rca.py", line 286, in <module>
    bn = engine.train_bayesian_network(dfs=[df])
  File "C:/Users/1000260871/Desktop/root cause analysis/PyRCA-main/pyrca/applications/example/rca.py", line 152, in train_bayesian_network
    bayesian_network.train(dfs=dfs)
  File "C:\python\lib\site-packages\pyrca\analyzers\bayesian.py", line 132, in train
    self._refine_parameters(lower_bound=0.01)
  File "C:\python\lib\site-packages\pyrca\analyzers\bayesian.py", line 138, in _refine_parameters
    assert cpd.values.shape[0] == 2, f"The cardinality of the variable {cpd.variable} should be = 2."
AssertionError: The cardinality of the variable conn_pool should be = 2.
```

I checked the cpp.values, it is **array([1.])**

why it happens? I didn't change anything for example.csv file

**Comment by Supamongkol** [comment]
Hi,  I found problem with some Data . I use this model with categorical data but I must use one hot encoding to change text to numeric to train model using PyRCA. and found "ValueError: Data correlation matrix is singular. Cannot run fisherz test. Please check your data."
.
 How to avoid this error . 
.
Thank you very much
